config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clinics
  resources :sales
  resources :consultations
  resources :line_items
  resources :bills, only: [:index]
  resources :payments
  resources :credit_notes
  resources :client_credits
  
  resources :invoices do
    resources :payments, only: [:new, :create], module: :invoices
  end
  
  root 'invoices#index'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  belongs_to :clinic
  
  has_many :line_items, dependent: :destroy
  has_many :payment_allocations, dependent: :destroy
  has_many :payments, through: :payment_allocations
  
  has_one :credit_note

  monetize :net_price_cents
  monetize :gross_price_cents
  monetize :tax_amount_cents
  monetize :discount_amount_cents
  monetize :amount_paid_cents
  monetize :balance_cents

  alias_attribute :parts, :payment_allocations
  alias_attribute :total, :gross_price
  
  def resources
    line_items.map(&:resource).uniq
  end
  
  def resource
    # A resource's line_items will always have the same invoice (if it exists)
    line_items.first&.resource
  end

  def amount_paid_cents
    payment_allocations.sum(:amount_cents)
  end

  def balance_cents
    return 0 unless gross_price_cents && amount_paid_cents
    gross_price_cents - amount_paid_cents
  end

  def unpayable?
    credit_note.present?
  end
  
  def paid?
    balance_cents <= 0
  end

  def part_paid?
    !paid? && amount_paid_cents > 0
  end

  def unpaid?
    !paid?
  end

  def open?
    unpaid?
  end

  def late?
    unpaid? && due_date < Date.today
  end

  def status
    return "Cancelled" if credit_note
    return "Error" if unpayable?
    return "Paid" if paid?
    return "Late" if late?
    return "Part Paid" if part_paid?
    return "Active"
  end

  def set_totals! save: true, resources: nil
    line_items = resources ? resources.map(&:line_items).flatten : self.line_items
    self.net_price_cents = line_items.map(&:net_price_cents).sum
    self.gross_price_cents = line_items.map(&:gross_price_cents).sum
    self.tax_amount_cents = line_items.map(&:tax_amount_cents).sum
    self.discount_amount_cents = line_items.map(&:discount_amount_cents).sum
    self.save! if save
  end
  
  def self.create_from_resource resource
    raise ArgumentError, "Resource must be a model" unless resource.is_a?(ApplicationRecord)
    raise StandardError, "Resource is not of a billable type" unless resource.respond_to? :billable?
    raise StandardError, "Resource is already billed" if resource.billed?
    raise StandardError, "Resource is not billable" unless resource.billable?
    
    ActiveRecord::Base.transaction do
      
      # Create the invoice
      invoice = Invoice.new

      # Set the invoice's basic information
      invoice.clinic = resource.clinic
      invoice.client = resource.client
      invoice.date = Date.today
      invoice.due_date = Date.today + 30.days

      invoice.set_totals! save: false, resources: [resource]
      
      # Save the invoice
      invoice.save!

      # Now set the line items to use this invoice
      resource.line_items.unbilled.update_all invoice_id: invoice.id

      # Return the invoice
      invoice
      
    end
    
  end

  def self.create_from_resources(resources = [])
    
    raise ArgumentError, "Resources must be an array" unless resources.is_a?(Array)
  
    grouped_resources = resources.group_by { |resource| [resource.clinic_id, resource.client_id] }
  
    invoice_ids = [] # Array to store created invoice IDs
  
    ActiveRecord::Base.transaction do
      grouped_resources.each do |(clinic_id, client_id), resources|
        # Create the invoice
        invoice = Invoice.new(clinic_id: clinic_id, client_id: client_id, 
                              date: Date.today, due_date: Date.today + 30.days)
  
        invoice.set_totals!(save: false, resources: resources)
        
        # Save the invoice
        invoice.save!
  
        # Collect the invoice ID
        invoice_ids << invoice.id
  
        # Set the line items to use this invoice
        resources.each do |resource|
          resource.line_items.unbilled.update_all(invoice_id: invoice.id)
        end
      end
    end
  
    invoice_ids # Return the collected invoice IDs
  end
  

  def issue_credit_note!
    ActiveRecord::Base.transaction do
      credit_note = CreditNote.create! invoice: self, clinic: self.clinic, client: self.client, date: Date.today
      self.line_items.each do |line_item|
        item = line_item.dup
        item.assign_attributes invoice: nil, resource: credit_note, unit_price_cents: -line_item.unit_price_cents
        item.save!
      end
      credit_note
    end
  rescue => e
    false
  end
  
end

app/controllers/invoices/payments_controller.rb
class Invoices::PaymentsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :set_invoice

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new new_params.merge(client: @invoice.client)
    
    if maximum_amount_exceeded?
      specified_amount = number_to_currency payment_params[:amount].to_f, unit: '€', locale: :fr
      @payment.errors.add :base, "Some important error message"
      @payment.errors.add :amount, "cannot be greater than the invoice balance, #{specified_amount} was specified"
      render :new, status: :unprocessable_entity
      return
    end

    ActiveRecord::Base.transaction do
      if @payment.save
        @invoice.payment_allocations.create payment: @payment, amount: payment_amount
        redirect_to @invoice, notice: "Payment successfully created"
      else
        render :new, status: :unprocessable_entity
      end
    end

  end

  private
  
  def set_invoice
    @invoice = Invoice.find params[:invoice_id]
  end

  def payment_params
    params.require(:payment).permit :date, :payment_method, :amount, :notes, :client_credit_id
  end

  def new_params
    payment_params.except :amount
  end

  def maximum_amount_exceeded?
    payment_params[:amount].to_f > @invoice.balance.to_f
  end

  def credit_method_selected?
    payment_params[:payment_method] == "client_credit" && payment_params[:client_credit_id].present?
  end

  def payment_amount
    return payment_params[:amount].to_f unless credit_method_selected?
    client_credit = ClientCredit.find payment_params[:client_credit_id]
    [@invoice.balance, client_credit.amount].min.to_f
  end
  
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    @invoices = Invoice.order id: :desc
  end

  def show
    @invoice = Invoice.find params[:id]
    @payment = Payment.new
  end

  def create
    invoice_ids = Invoice.create_from_resources resources
    if invoice_ids.size == 1
      @invoice = Invoice.find invoice_ids.first
      redirect_back_or_to @invoice, notice: "Invoice #{@invoice.id} created"
    elsif invoice_ids.size > 1
      redirect_back_or_to invoices_path, notice: "Invoices #{invoice_ids.join(', ')} created"
    else
      redirect_back_or_to @resource, alert: "Invoice(s) could not be created"
    end
  end

  private

  def find_resource_from_reference reference
    return nil unless reference.present?
    resource_name, _, id = reference.rpartition("_")
    resource_type = resource_name.classify.constantize
    resource_type.find(id)
  end

  def resources
    params[:resources].map { |reference| find_resource_from_reference(reference) }
  end

end

app/helpers/clients/invoices_helper.rb
module Clients::InvoicesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.slim
div class="flex flex-col gap-4"

  h1 class="font-bold text-2xl" Invoices

  table
    thead
      th ID
      th Date
      th Client
      th Clinic 
      th Resource
      th Total
      th Status
    tbody
      - @invoices.each do |invoice|
        tr
          td = link_to invoice.id, invoice, class: "hover:underline text-black"
          td = link_to invoice.date.to_fs, invoice, class: "hover:underline text-black"
          td = link_to invoice.client.name, invoice.client, class: "hover:underline text-black"
          td = invoice.clinic.name
          td = link_to invoice.resource.identifier, invoice.resource, class: "hover:underline text-black"
          td = invoice.gross_price
          td = invoice.status

app/views/invoices/show.html.slim
div class="flex flex-col gap-4"

  h1 class="font-bold text-2xl" = "Invoice ##{@invoice.id}"
  
  h6 Resources
  ul
    - @invoice.resources.each do |resource|
      li = link_to resource.identifier, resource

  = link_to "Return to Invoices", invoices_path, class: "underline text-black"

  - if @invoice.credit_note
    = link_to @invoice.credit_note.identifier, @invoice.credit_note, class: "underline text-black"
  - else
    = button_to "Issue credit", credit_notes_path(invoice_id: @invoice.id), method: :post, class: "underline text-black", data: { turbo_confirm: "Are you sure?" }

  = link_to "Client: #{@invoice.client.name}", @invoice.client

  div class="flex flex-col gap-4"

    - @invoice.resources.each do |resource|
      = render "resources/items-table", resource: resource
  
    h6 = "Total: #{number_to_currency @invoice.total}"
    
    h6 class="bg-yellow-200" = "Status: #{@invoice.status}"

  - unless @invoice.paid?    
    = link_to "Pay invoice", new_invoice_payment_path(@invoice), class: "underline text-black"
  
  - if @invoice.parts.any?
    h5 Payments
    - @invoice.parts.each do |part|
      = link_to "#{part.created_at.to_fs} | #{part.payment.payment_method} | #{number_to_currency(part.amount, locale: :fr, unit: "€")}", part.payment