config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clinics
  resources :sales
  resources :consultations
  resources :line_items
  resources :bills, only: [:index]
  resources :payments
  resources :credit_notes
  resources :client_credits
  
  resources :invoices do
    resources :payments, only: [:new, :create], module: :invoices
  end
  
  root 'invoices#index'
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  include Billable
  belongs_to :clinic
  belongs_to :client
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController

  def index
    @consultations = Consultation.order(date: :desc)
  end

  def show
    @consultation = Consultation.find params[:id]
    @act_item = ActItem.new resource: @consultation
    @product_item = ProductItem.new resource: @consultation
  end

  def new
    @consultation = Consultation.new
  end
  
  def create
    @consultation = Consultation.new consultation_params
    if @consultation.save
      redirect_to @consultation, notice: "Consultation created"
    else
      render :new
    end
  end

  private

  def consultation_params
    params.require(:consultation).permit(:date, :client_id, :clinic_id, :motive)
  end
  
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/index.html.slim
h1 class="text-xl" Consultations

= link_to 'New consultation', new_consultation_path, class: 'underline text-black'

table
  thead
    tr
      th Date
      th Client
      th Clinic
      th Motive
  tbody
    - @consultations.each do |consultation|
      tr
        td = link_to consultation.date.to_fs, consultation
        td = link_to consultation.client.name, consultation.client
        td = link_to consultation.clinic.name, consultation.clinic
        td = consultation.motive.presence || "No motive"

app/views/consultations/new.html.slim
h1 Add a new consultation

= link_to "Return to consultations", consultations_path, class: "underline text-black"

= simple_form_for @consultation do |form|
  = form.input :date
  = form.association :clinic
  = form.association :client, collection: Client.order(:name)
  = form.input :motive
  = form.button :submit

app/views/consultations/show.html.slim
div class="flex flex-col gap-4"

  h1 class="font-bold text-2xl" = @consultation.identifier

  = link_to "Return to consultations", consultations_path, class: "underline text-black"

  p = "Clinic: #{@consultation.clinic.name}"
  p 
    span Client: 
    = link_to @consultation.client.name, @consultation.client, class: "hover:underline text-black"
  
  - if @consultation.invoice
    = link_to "Invoice ##{@consultation.invoice.id}", @consultation.invoice, class: "underline text-black"
  - else
    - if @consultation.to_be_billed?
      = button_to "Invoice items", invoices_path(resources: [@consultation.record_reference]),\
        class: "underline text-black", data: { turbo_confirm: "Invoice this consultation?" }
    - else
      p = "This consultation is not billable"
  
  h4 Add an act
  = render "line_items/form", resource: @consultation, type: "ActItem"

  h4 Add a product
  = render "line_items/form", resource: @consultation, type: "ProductItem"
  
  = render "resources/items-table", resource: @consultation, hide_title: true