config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clinics
  resources :sales
  resources :consultations
  resources :line_items
  resources :bills, only: [:index]
  resources :payments
  resources :credit_notes
  resources :client_credits
  
  resources :invoices do
    resources :payments, only: [:new, :create], module: :invoices
  end
  
  root 'invoices#index'
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales, dependent: :destroy
  has_many :invoices, dependent: :nullify
  has_many :line_items, dependent: :nullify
  has_many :payments, dependent: :nullify
  has_many :client_credits, dependent: :nullify

  alias_attribute :credits, :client_credits

  monetize :total_credit_cents, :unbilled_amount_cents
  
  def unbilled_resources
    items = line_items.to_be_billed
    items.map(&:resource).uniq
  end

  # Generate a list of references for the unbilled resources, we cannot simply pass ids to invoice controller as many types of resources are involved
  def unbilled_references
    unbilled_resources.map(&:record_reference)
  end

  def unbilled_amount_cents
    line_items.to_be_billed.sum(&:gross_price_cents)
  end

  def available_credits
    client_credits.select(&:active?)
  end

  def total_credit_cents
    available_credits.sum(&:amount_remaining_cents)
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.order :name
  end

  def show
    @client = Client.find params[:id]
  end
  
end

app/helpers/clients/invoices_helper.rb
module Clients::InvoicesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/index.html.slim
h1 Clients

- @clients.each do |client|
  p = link_to client.name, client

app/views/clients/show.html.slim
h1 class="font-bold text-2xl mb-6" = @client.name

div class="flex flex-col gap-4"

  = link_to "Return to Clients", clients_path, class: "underline text-black"

  - if @client.unbilled_resources.any?
    h4 Bons à facturer
    p = "This client has #{pluralize(@client.unbilled_resources.count, "bill")} \
      totalling #{euros(@client.unbilled_amount)} ready to be invoiced"
    = button_to "Invoice now", invoices_path(resources: @client.unbilled_references),\
      class: "underline text-black",\
      data: { turbo_confirm: "Invoice unbilled resources?" }
    ul
      - @client.unbilled_resources.each do |resource|
        li 
          = link_to resource.identifier, resource
          = button_to "Invoice now", resource_invoice_path(resource), class: "underline text-black", data: { turbo_confirm: "Are you sure you would like to invoice this #{resource.class.name.titleize}?" }

  - if @client.invoices.any?
    h4 Factures
    ul
      - @client.invoices.each do |invoice|
        li = link_to invoice.identifier, invoice

  - if @client.payments.any?
    h4 Recent payments
    ul
      - @client.payments.order(created_at: :desc).limit(5).each do |payment|
        li = link_to "#{payment.created_at.to_fs} | #{number_to_currency(payment.amount, locale: :fr, unit: "€")}", payment
  
  - if @client.available_credits.any?
    div
      h4 Client has credits available
      p = "Total credit: #{number_to_currency(@client.total_credit, locale: :fr, unit: "€")}"