config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clinics
  resources :sales
  resources :consultations
  resources :line_items
  resources :bills, only: [:index]
  resources :payments
  resources :credit_notes
  resources :client_credits
  
  resources :invoices do
    resources :payments, only: [:new, :create], module: :invoices
  end
  
  root 'invoices#index'
end

app/models/sale.rb
class Sale < ApplicationRecord
  include Billable
  
  belongs_to :clinic
  belongs_to :client

  def title
    to_s + " | " + date.to_fs
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
    @sales = Sale.order(date: :desc)
  end

  def show
    @sale = Sale.find params[:id]
    @line_item = ProductItem.new resource: @sale
  end
  
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/index.html.slim
h1 class="text-xl" Sales

= link_to 'New sale', new_sale_path, class: 'underline text-black'

table
  thead
    tr
      th Date
      th Client
      th Clinic
      th Num products
  tbody
    - @sales.each do |sale|
      tr
        td = link_to sale.date.to_fs, sale
        td = link_to sale.client.name, sale.client
        td = link_to sale.clinic.name, sale.clinic
        td = sale.line_items.count

app/views/sales/show.html.slim
div class="flex flex-col gap-4"

  h1 class="font-bold text-2xl" = "Sale ##{@sale.id}"

  = link_to "Return to Sales", sales_path, class: "underline text-black"

  p = "Clinic: #{@sale.clinic.name}"
  p 
    span Client: 
    = link_to @sale.client.name, @sale.client, class: "hover:underline text-black"
  
  - if @sale.invoice
    = link_to "Invoice ##{@sale.invoice.id}", @sale.invoice, class: "underline text-black"
  - else
    p Invoice: Not yet invoiced
    - if @sale.billable?
      - invoice_path = invoices_path(resource_id: @sale.id, resource_type: @sale.class.name)
      = button_to "Invoice items", invoice_path, class: "underline text-black"
    - else
      p = "This sale is not billable"
  
  h4 Produits

  = render "line_items/form", resource: @sale, type: "ProductItem"
  
  = render "resources/items-table", resource: @sale, hide_title: true